services:
  app:
    container_name: myride-app
    build: .
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql-db
    image: mysql:8.4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_ride
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.4
    ports:
      - 6379:6379
    restart: always